import { useState } from 'react'

const columns = ['recordCode', 'company', 'category', 'name', 'brand', 'model', 'description', 'serialNumber', 'purchaseDate', 'purchasePrice', 'supplier', 'poNumber', 'invoiceNumber', 'warrantyExpirationDate', 'issueDate', 'accountableTo', 'department', 'location', 'status', 'condition', 'remarks']
function parseCsv(text) {
  const rows = []; let row = []; let value = ''; let quoted = false
  for (let i = 0; i < text.length; i += 1) { const c = text[i]; if (c === '"' && text[i + 1] === '"') { value += '"'; i += 1 } else if (c === '"') quoted = !quoted; else if (c === ',' && !quoted) { row.push(value.trim()); value = '' } else if ((c === '\n' || c === '\r') && !quoted) { if (value || row.length) { row.push(value.trim()); rows.push(row); row = []; value = '' } } else value += c }
  if (value || row.length) { row.push(value.trim()); rows.push(row) }
  const headers = (rows.shift() || []).map((header) => header.trim())
  return rows.filter((values) => values.some(Boolean)).map((values) => Object.fromEntries(headers.map((header, index) => [header, values[index] || ''])))
}
export function EquipmentImport({ api, onClose, onImported }) {
  const [rows, setRows] = useState([]); const [fileName, setFileName] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  function downloadTemplate() { const blob = new Blob([[columns.join(','), columns.map(() => '').join(',')].join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'office-equipment-import-template.csv'; link.click(); URL.revokeObjectURL(link.href) }
  async function importRows() { setBusy(true); setError(''); try { const result = await api('/equipment/import', { method: 'POST', body: JSON.stringify({ rows }) }); onImported(result.items); onClose() } catch (failure) { setError(failure.message) } finally { setBusy(false) } }
  return <div className='inventory-modal-backdrop'><section className='inventory-modal'><div className='inventory-modal-head'><div><p className='eyebrow'>Office Equipment</p><h2>Import Excel / CSV</h2></div><button onClick={onClose}>Close</button></div><p>Use the template to prepare equipment rows. Save an Excel sheet as CSV before importing.</p><button type='button' className='inventory-secondary' onClick={downloadTemplate}>Download template</button><label>Select file<input type='file' accept='.csv,text/csv,.xlsx,.xls' onChange={async (event) => { const file = event.target.files[0]; if (!file) return; setFileName(file.name); if (!file.name.toLowerCase().endsWith('.csv')) { setError('Please save the Excel file as CSV UTF-8 before importing.'); setRows([]); return } setRows(parseCsv(await file.text())); setError('') }} /></label>{fileName ? <p>{fileName} · {rows.length} rows ready</p> : null}{error ? <p role='alert' className='inventory-error'>{error}</p> : null}{rows.length ? <div className='inventory-table-wrap'><table><thead><tr>{columns.slice(0, 6).map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.slice(0, 5).map((row, index) => <tr key={index}>{columns.slice(0, 6).map((column) => <td key={column}>{row[column] || '—'}</td>)}</tr>)}</tbody></table>{rows.length > 5 ? <p>Showing first 5 rows of {rows.length}.</p> : null}</div> : null}<div className='inventory-form-actions'><button onClick={onClose}>Cancel</button><button className='inventory-primary' disabled={!rows.length || busy} onClick={importRows}>{busy ? 'Importing…' : `Import ${rows.length || ''} equipment`}</button></div></section></div>
}
